### ISSUE TITLE
Custom cert definition, script error

### ISSUE THREAD

**Issue by Miky028** [ronivay/xen-orchestra-docker#11]
When I define variable HTTPS_PORT, CERT_PATH and KEY_PATH then error occur.

Environment variables:
HTTPS_PORT=443
CERT_PATH='/cert.pem'
KEY_PATH='/cert.key'

Volumes definition:
-v /mnt/user/appdata/XO/certs/cert.pem:/cert.pem \
-v /mnt/user/appdata/XO/certs/cert.key:/cert.key \

Files are accessible within the container.

LOG:
`✖ Unexpected character, expecting string, number, datetime, boolean, inline array or inline table at row 102, col 8, pos 2770:
101: autoCert = true
102> cert = /cert.pem
       
             ^

103: key = /cert.key
TomlError: Unexpected character, expecting string, number, datetime, boolean, inline array or inline table at row 102, col 8, pos 2770:
101: autoCert = true
102> cert = /cert.pem

             ^

103: key = /cert.key`

It is pointing to the slash.

**Comment by ronivay** [comment]
Hi,

Are you using docker-compose or defining the variables manually? What version of docker/docker-compose are you using? Can you copy paste the exact docker run string or docker-compose.yml file that you use. I can't reproduce this with the example `docker-compose.yml`. The error message is quite clear though, the Xen Orchestra config toml file is expecting the value to be surrounded with single quotes which for you are dropping out for some reason.

**Comment by Miky028** [comment]
Hi,
I manually added container to the unRAID. Startup script generated:
`docker run -d --name='XO' --net='bridge' --privileged=true -e HOST_OS="Unraid" -e 'CERT_PATH'='/cert.pem' -e 'KEY_PATH'='/cert.key' -e 'TZ'='Europe/Prague' -e 'HTTP_PORT'='80' -e 'HTTPS_PORT'='443' -p '8080:80/tcp' -p '8443:443/tcp' -v '/mnt/user/appdata/XO/certs/cert.pem':'/cert.pem':'rw' -v '/mnt/user/appdata/XO/certs/cert.key':'/cert.key':'rw' -v '/mnt/user/appdata/XO/redis':'/var/lib/redis':'rw' -v '/mnt/user/appdata/XO/xo-server':'/var/lib/xo-server':'rw' --stop-timeout 60 --restart unless-stopped --cap-add sys_admin --device /dev/fuse 'ronivay/xen-orchestra:latest'`

Environment variable in the docker shell:
`# set
CERT_PATH='/cert.pem'
HOME='/root'
HOSTNAME='041c1d13890d'
HOST_OS='Unraid'
HTTPS_PORT='443'
HTTP_PORT='80'
IFS=' 
'
KEY_PATH='/cert.key'
NODE_VERSION='14.17.6'
OPTIND='1'
PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
PPID='0'
PS1='# '
PS2='> '
PS4='+ '
PWD='/etc/xen-orchestra/packages/xo-server'
TERM='xterm'
TZ='Europe/Prague'
YARN_VERSION='1.22.5'`


I just added quotation marks to the form to this variable and everything is working fine. Thanks for advice.

**Comment by ronivay** [comment]
Hi,

Thank you. Great that adding quotes helped. I added a mention about this to README for now. Could just revert the variable value handling so that it wouldn't need the quotes, but that could possibly break some existing setups, so some unnecessarily complicated checks would be needed :) leaving like this for now.
