### ISSUE TITLE
ssl connection to XCP-NG using an internal/custom CA certificate

### ISSUE THREAD

**Issue by headwhacker** [ronivay/xen-orchestra-docker#14]
I have setup XCP-NG and XO using a custom certificates. I can access both Web UIs just fine using HTTPS.

However, I can't add the XCP-NG host as a server in XO using https. It always show this error

"self signed certificate in certificate chain"

Reading the XO documentation and github link below I see 2 things which are recommended to be set:
https://xen-orchestra.com/docs/configuration.html#link-to-xo-web
https://github.com/vatesfr/xen-orchestra/issues/2659

1. Add the custom CA to /etc/ssl/certs in XO
2. Add "Environment=NODE_OPTIONS=--use-openssl-ca"  in /etc/systemd/system/xo-server.service

I can see these are applicable with XO installed from the sources and running in a VM or bare metal.

Is there a way this can be applied using this docker image? Or is there a way I can add an xen server via https using custom CAs.

**Comment by ronivay** [comment]
When you add the server to XO, there's a button to enable "Unauthorized Certificates". Did you try that?

**Comment by headwhacker** [comment]
Hi,

Yes, it will work if I enable "Unauthorized Certificates". But that will make the connection between XO and XCP-NG unsecured.

I can mount a volume then add my custom CA to /etc/ssl/certs. But I can't figure out how to set  the "use-openssl-ca" option.

Hopefully, this can be cosidered an option on future versions for this container. Possibly make is available as an env variable that can be set for the container?

Thanks
-Mario

**Comment by ronivay** [comment]
Hi,

No it doesn't, traffic is as much encrypted as it would be with a trusted CA. As XO documentation says, if you manage your own CA, using this feature might make sense. Something like that is usually used in bigger business environments where you'd have multiple hosts and want to centrally manage issuing and lifetime of those certificates. Sure it adds a level of security by blocking traffic if CA doesn't match, but doesn't change the way XO and host communicate in any way. 

Sure i can take a look if this can be implemented into the container.

**Comment by headwhacker** [comment]
Ok thanks. I did enable "Unauthorized Certificates" for now. Would be cool to expose this option as container variables. Thanks for looking into this.

**Comment by headwhacker** [comment]
Hi Roni, that worked like a charm. thanks.
