### ISSUE TITLE
invalid credentials

### ISSUE THREAD

**Issue by dezren39** [ronivay/xen-orchestra-docker#15]
Hello,

I had a docker-compose file locally running which worked, but recently I retried on my windows machine and the image boots, I can see the login, but the default credentials consistently just register 'invalid credentials' is there something I am missing?

Is this possibly related to this?
https://github.com/ronivay/XenOrchestraInstallerUpdater/issues/133

**Comment by dezren39** [comment]
or maybe one of these two:
https://github.com/ronivay/XenOrchestraInstallerUpdater/issues/134
https://github.com/ronivay/XenOrchestraInstallerUpdater/issues/135
I played around trying to fix it on my end, but am not sure how to address without rebuilding the image locally. I may look into that later but don't want to waste time if it's already fixed in a future patch push. :-)

**Comment by ronivay** [comment]
Hi,

yeah the issue 135 is most likely related. i built and pushed a new container image now. try to pull the new latest tag and let me know if it fixes the issue.

**Comment by ronivay** [comment]
@dezren39 can you confirm if this helped? Thanks.

**Comment by dezren39** [comment]
hey ! I absolutely will do that tonight. lyk

**Comment by dezren39** [comment]
Hi! Thank you, it does appear to be working right for me now. However, I had done a hard reset and used an old tag before upgrading to this new tag, so I don't know if will be exactly like if I had upgraded, it broke, then I upgraded it to this new version.

**Comment by ronivay** [comment]
I'm pretty sure all the redis related fixes would've helped to the original situation as well. I'm gonna call this one solved. 

Thanks for reporting and testing.
