### ISSUE TITLE
Build didn't run due to repo inactivity.

### ISSUE THREAD

**Issue by ajpri** [ronivay/xen-orchestra-docker#19]
I use this and watchtower to auto-update XO weekly. Saw my container didn't update last night.

Looked at https://github.com/ronivay/xen-orchestra-docker/actions/workflows/build.yml and saw "This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days. Enable this workflow to resume scheduled runs."

**Comment by ronivay** [comment]
Hi,

Thanks, i've missed this was disabled due to inactivity. Enabled now.

**Comment by ronivay** [comment]
schedule works again
