### ISSUE TITLE
NTFS support?

### ISSUE THREAD

**Issue by Miky028** [ronivay/xen-orchestra-docker#20]
HOST TrueNAS-SCALE-22.02.4
Docker XO commit b63c4
xo-server 5.104.0
xo-web 5.105.0

Issue
Trying to restore file from NTFS partition.

Installation logfile
xo:api WARN admin | backupNg.listFiles(...) [213ms] =!> Error: Command failed: mount --options=loop,ro,norecovery,sizelimit=71571603456,offset=368050176 --source=/tmp/qfs18qcazn/vhd0 --target=/tmp/u1jfb36ljvk
mount: /tmp/u1jfb36ljvk: unknown filesystem type 'ntfs'.

_________________________________________________

HOST UNRAID Version: 6.9.2
Docker XO commit 31f85 (tag 5.109.0)
xo-server 5.109.0
xo-web 5.111.0

Issue
Trying to restore file from NTFS partition.

Installation logfile
xo:api WARN admin | backupNg.listFiles(...) [367ms] =!> Error: Command failed: mount --options=loop,ro,norecovery,sizelimit=71571603456,offset=368050176 --source=/tmp/fk9v3yqexdp/vhd0 --target=/tmp/i32r5s4zroc
mount: /tmp/i32r5s4zroc: wrong fs type, bad option, bad superblock on /dev/loop4, missing codepage or helper program, or other error.

________________________________________________

I'm certain that in some of previous version it was working.

PS: Sorry for wrong repository.

**Comment by ronivay** [comment]
Hey,

I guess this is due to lack of `ntfs-3g` package within the container. It has never been there. I unfortunately lack a bit of testing possibility for this as i don't have any windows VMs inside XCP-ng to test with. If you'd like to help out and experiment, you could build custom version of the container (instructions in README), just edit this line first from `Dockerfile`

```
RUN apt update && \
    apt install -y redis-server libvhdi-utils python2-minimal python-jinja2 lvm2 nfs-common netbase cifs-utils ca-certificates monit procps curl
```

to 

```
RUN apt update && \
    apt install -y redis-server libvhdi-utils python2-minimal python-jinja2 lvm2 nfs-common netbase cifs-utils ca-certificates monit procps curl nfts-3g
```

**Comment by ronivay** [comment]
Have you had a change to give this a spin?

**Comment by ronivay** [comment]
ntfs-3g package is now added to container which should address the issue. if it doesn't. please reopen this issue or create a new one.
