### ISSUE TITLE
File Restore Not Working

### ISSUE THREAD

**Issue by marcpope** [ronivay/xen-orchestra-docker#21]
I am running XenOrchestra Docker Container on a Synology NAS. I am running it will Full Permissions and everything seems to work great except one thing, it won't do the File Restore. Backups and VM Restore works good. For File Restore, I can get to picking the partitions, but then doesn't show the files/folders in the partitions. The backups are on NFS Partitions which are hosted on the parent Synology NFS File Shares and that connection seems to be fine. I am wondering if there is some package missing to get files to extract out of the images?

Hardware:
- Synology 1621+ 
- AMD Ryzen V1500B processor
- 32GB RAM, 4 Cores

**Comment by marcpope** [comment]
I found in XO Forums that we might need this: apt-get install ntfs-3g

https://xcp-ng.org/forum/topic/3629/file-restore-not-working-little-red-triangle/23

How can we include this in the docker image or add it?

**Comment by ronivay** [comment]
https://github.com/ronivay/xen-orchestra-docker/issues/20

Please continue on that issue. Help is appreciated as i currently lack possibility to test this.

**Comment by marcpope** [comment]
can you confirm if file restore works in other environments with this docker setup?

**Comment by ronivay** [comment]
Yes file restore in general works. As the issue i linked suggests, restoring from disks containing NTFS filesystem is most likely broken but there hasn't been much help from the community to test it out :)

**Comment by marcpope** [comment]
A little more info. This is the error that Xen Orchestra is reporting once clicking on a partition to show the files:

```
Command failed: mount --options=loop,ro,norecovery --source=/dev/centos/root --target=/tmp/ibm57sco23
mount: /tmp/ibm57sco23: failed to setup loop device for /dev/centos/root.
```

I am guessing this is something simple. The reason I like to run XO on my Synology is that is where all my backups are, so backing up is 2x quicker than all the backups have to traverse through the network. I have 40TB of data I backup daily, so this makes a huge difference.

**Comment by ronivay** [comment]
I assume you've read the readme and docker-compose example about loopback devices (heavily related to file restore)? I unfortunately have no idea how containers are setup on synology so can't really give you a step by step instructions how to set that up properly.
