### ISSUE TITLE
Is it necessary to register with XOA in the cloud to use this container?

### ISSUE THREAD

**Issue by furrnace** [ronivay/xen-orchestra-docker#22]
This is obviously a XO nood question, but it would strike probably everyone who is new to XO. Maybe this could be answered in the github project info text to avoid the following confusion:

When starting the container and opening the web UI there is a red questions mark in the XOA menu section. also other sections as Hub and XOSAN say "Try XOA for free and deploy it here".  

<img width="796" alt="Screenshot 2023-04-14 at 22 03 18" src="https://user-images.githubusercontent.com/110343153/232144950-45e756aa-7846-447b-8eef-3557076dbb16.png">

My current (and possible incomplete or wrong) understanding is that this container is an instance of XOA. So what would happen if I went through the procedure to deploy XOA through the containers XO web UI? would this overwrite parts of the container? Is this encouraged or discouraged?

Also if one would run through "deploy XOA", would the Updates button then be usable and do the "right thing"? Or is it discouraged to use Update in the Web UI and rather pull a new version of the container?

As there is no information on these in the container description, I am unsure how to proceed here, as I do not wish to cripple the container accidently by deploying XOA and using Update.

**Comment by ronivay** [comment]
Hey,

There's two ways of running Xen Orchestra.

XOA is the official appliance offered by the company behind Xen Orchestra which comes with limited feature set without purchasing a subscription. Clicking the deploy link will just guide you through the appliance setup, doesn't do anything to your docker XO instance.

XO from sources is another method where you essentially install the Xen Orchestra from sources with all features included, the way this container also uses. There are certain things which are XOA only, like the GUI updater, XOSAN etc. They are part of the added value you get from running the official appliance, also known as XOA.

**Comment by ronivay** [comment]
Yeah exactly. I'll look into making it more clear in README that XO from sources != XOA.
