### ISSUE TITLE
issue with remotes

### ISSUE THREAD

**Issue by themonkeymixer** [ronivay/xen-orchestra-docker#23]
Hi

I am having an issue with backup remotes and I have reached out to xcp directly 
https://github.com/vatesfr/xen-orchestra/issues/6818

Just wanted to make you aware in case the issue is on your side.

The only thing that stood out was to ensure cifs-utils is installed on the container.
From this post
https://xcp-ng.org/forum/topic/2169/backups-to-smb-remote-failing/12

Please let me know if you have any insights.

**Comment by ronivay** [comment]
Hey,

Thanks. Most likely something inside the container that prevents this from working. I can reproduce it while it works fine on installation with https://github.com/ronivay/XenOrchestraInstallerUpdater. I'll look into it.

**Comment by ronivay** [comment]
Your container is simply missing required capabilities to be able to mount remotes. There was one additional capability required to mount SMB shares based on tests i did. Updated README to include that in https://github.com/ronivay/xen-orchestra-docker/pull/24

After adding proper permissions to container, i was able to mount SMB share without issues.
