### ISSUE TITLE
No vm or host stats

### ISSUE THREAD

**Issue by stgordon** [ronivay/xen-orchestra-docker#3]
VM & host stats show "no stats". I also see the following in the logs:

"2020-05-24T13:49:14.276Z xo:api WARN sgordon | vm.stats(...) [21s] =!> FaultyGranularity: Unable to get the true granularity: 60 "

**Comment by ronivay** [comment]
Hi,

No an issue related to this script, so closing.

This could be either your XO vm or xcp-ng/xenserver time not in sync so you might want to check that at least.

**Comment by stgordon** [comment]
> Hi,
> 
> No an issue related to this script, so closing.
> 
> This could be either your XO vm or xcp-ng/xenserver time not in sync so you might want to check that at least.

Ha! I found my little Raspberi Pi (nameserver/NTP/etc) was down and was rebooting it as soon as you replied. Stats are BACK! Thanks, fella!
